name: Go build and test CLI TEST

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'put one commit hash'
        type: string
        required: true

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: '1.22.x'

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - name: "Testing manual workflow"
        run: echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
