name: Create Executables TEST

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  handle_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: |
          if [ -z "${{ github.event.inputs.base_tag }}" ]; then
            LATEST_TAG=$(git tag -l --sort=-v:refname | head -n 1 2>/dev/null || echo "v0.0.0")
            echo "base_tag=${LATEST_TAG}" >> $GITHUB_ENV
          else
            echo "base_tag=${{ github.event.inputs.base_tag }}" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.base_tag }}

      - name: Example Action Step
        run: echo "This step runs when a new tag is pushed ${{ github.event.inputs.base_tag }}"
