name: Go build and test CLI TEST

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        type: choice
        options:
          - major
          - minor
          - patch
        required: true
      base_tag:
        description: 'Base tag to bump from (default: highest tag, format : x.x.x)'
        type: string

concurrency:
  group: cd-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GIT_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  GO_VERSION: '1.22.x'
  OUTPUT_PATH: './output'


jobs:
  create_tag:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.share.outputs.commit_sha }}
      new_version: ${{ steps.share.outputs.new_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine commit SHA
        id: get_commit
        run: |
            BASE_COMMIT=$(git rev-parse HEAD)
            echo "commit_sha=${BASE_COMMIT}" >> $GITHUB_ENV
      - name: Get base tag
        id: get_base_tag
        run: |
          if [ -z "${{ github.event.inputs.base_tag }}" ]; then
            BASE_TAG=$(git tag -l --sort=-v:refname | head -n 1 2>/dev/null || echo "v0.0.0")
            echo "base_tag=${BASE_TAG}" >> $GITHUB_ENV
          else
            echo "base_tag=${{ github.event.inputs.base_tag }}" >> $GITHUB_ENV
          fi
      - name: Calculate new version
        id: calculate_version
        run: |
          echo "Current version: ${{ env.base_tag }}"
          version=${{ env.base_tag }}
          version=${version#v}
          major=$(echo $version | cut -d. -f1)
          minor=$(echo $version | cut -d. -f2)
          patch=$(echo $version | cut -d. -f3)

          case ${{ github.event.inputs.release_type }} in
            major)
              major=$((major + 1))
              minor=0
              patch=0
              ;;
            minor)
              minor=$((minor + 1))
              patch=0
              ;;
            patch)
              patch=$((patch + 1))
              ;;
            *)
              echo "Invalid release type"
              exit 1
          esac

          new_version="v${major}.${minor}.${patch}"
          echo "new_version=${new_version}" >> $GITHUB_ENV
          echo "New version: $new_version"
      - name: Create new tag
        uses: actions/github-script@v7
        with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              script: |
                const newVersion = process.env.new_version;
                const commitSha = process.env.commit_sha;
                github.rest.git.createRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: `refs/tags/${newVersion}`,
                  sha: commitSha,
                });

      - name: Share SHA and Tag
        id: share
        run: |
              echo "commit_sha=$commit_sha" >> $GITHUB_OUTPUT
              echo "new_version=$new_version" >> $GITHUB_OUTPUT
              echo "base_tag=$base_tag" >> $GITHUB_OUTPUT
#code from paren (create-and-upload-executables.yml)
  create_executables:
    needs: create_tag
    runs-on: ubuntu-latest
    steps:
      - name: get commit sha
        run: |
            echo "commit_sha=${{ needs.create_tag.outputs.commit_sha }}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.commit_sha }}

  create_release_draft:
      needs: [create_tag, create_executables]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Zip executables
          run: |
            OUTPUT_PATH="./docs"
            ZIP_NAME="executables.zip"
            zip -r $ZIP_NAME $OUTPUT_PATH
            echo "zip_name=$ZIP_NAME" >> $GITHUB_ENV
        - name: Release
          uses: softprops/action-gh-release@v2
          with:
            draft: true
            tag_name: ${{ needs.create_tag.outputs.new_version }}
            generate_release_notes: true
            files: ${{ env.zip_name }}
